# Generated by Django 5.2.7 on 2025-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanStart', '0002_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='casas/'),
        ),
    ]
