# Generated by Django 5.2.7 on 2025-12-01 18:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanStart', '0003_alter_casa_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='locacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
